import "./globals.css";
import styles from "./layout.module.css";
import type { Metadata } from "next";
import { NavBar } from "@/app/NavBar";
import { Header } from "@/app/Header";
import { Roboto } from "next/font/google";
import { getTodos } from "@/app/todolist/getTodos";
import { DeveloperBoard } from "@mui/icons-material";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["100", "300", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await getTodos();
  return (
    <html lang="en" className={roboto.className}>
      <body className={`${styles.gridContainer} bg-gray-500/50`}>
        <Box
          className={`${styles.topLeft}`}
          display="flex"
          justifyContent="center"
          alignItems="center"
        >
          <DeveloperBoard color="success" fontSize="large" />
        </Box>
        <div className={`${styles.header} bg-amber-500`}>
          <Header posts={posts} />
        </div>
        <div className={`${styles.left} bg-red-200`}>
          <NavBar />
        </div>
        <div className={`${styles.content}`}>{children}</div>
      </body>
    </html>
  );
}
